-- AlterTable
ALTER TABLE "users" ALTER COLUMN "dateBirth" DROP NOT NULL,
ALTER COLUMN "tugPlate" DROP NOT NULL,
ALTER COLUMN "vehicleType" DROP NOT NULL,
ALTER COLUMN "vehicleType" SET DEFAULT 'CAMPER';
