name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: turistaRV
          
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET_ACCESS_TOKEN: 9ab0f1edab31a2a241cf1e3225d14931
          JWT_SECRET_REFRESH_TOKEN: 62a4861e75e1c95b39c0469e3d18e666
          JWT_EXPIRES_IN_REFRESH_TOKEN: 7d
          JWT_EXPIRES_IN_ACCESS_TOKEN: 10m
          SENDGRID_API_KEY: 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
          APP_URL_DEVLOPMENT: http://localhost:3333/api
          APP_URL_PRODUCTION: https://api-olharlaser.onrender.com/api
          NODE_ENV: development
          DATABASE_URL: postgresql://docker:docker@localhost:5432/turistaRV?schema=public
          CHARACTERS: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
          FIREBASE_BUCKET: gs://olharlaser.appspot.com
          FIREBASE_CLIENT_EMAIL: firebase-adminsdk-zxkjk@olharlaser.iam.gserviceaccount.com
          FIREBASE_PROJECT_ID: olharlaser
          FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDdd4udzYKa40a5\nX6iizblktICNpsR9H+Gu5a6pdZjCefDHHEnAfLDyc5s0JLHzPVL20oEFrYO7j9Z/\nqCaUdvOsL6pTVy6n1Ppb/McHO55zB/AdrPr9uTDWItze+QzKIhKwbGMIgOoZce7U\n5nbGXAIUz7fmB+QrmHy7+D6PR/ENQAg2n0EcAvU7ubyakkWBZu85v0WRrpq0p5ue\nvEORbJHxrJb8DqoU0d7VFmaDeLOYz5Xst7pJFud5QUtHuQX/KQJESjFFCZmI5Rot\ncYmEE1zuz57HCSlroosLAeQIJuUNmAeEN5TvxptNtfDAujujhcQFDyR7+RDN6NNU\nOaOXLDYdAgMBAAECggEAOqhFFGCwLPHxc3vAoI44glHEksAO3s0o6zfuUPfSo//E\nJBh7+D2OaEjyXJczgqdFaBZNEgHpGC56s4kH3t66n2pohHZc5xrjzKVg2auSxgje\nMh30xGreYnkNYwk3t/naVVv/xurOFjs09LKt1s/bxUNXA9gnONzEfMy9VRnK4KUM\n5Gkc3hibP8t9DDCkcOG5b9pA5TR6cc/QCa5yfyKIQJvBnSBr+q9SCsJv9sMwv9Y1\nSio3okO30RSAO2oHNEZXBneXC7HNC5noU3X3cjSkgvkqmztMPmuHFQtzEbrWipkr\nE0Fsl1we4xUwxA6vRULIE5eimCALEAbBnB0+NIC1iQKBgQDwlilEbjo6SScgG305\nm3CQxa4+jlC866+PULUuaIpHFq9JI9lTS98j6NPa++scw4QHH4Xfo3jdkecNGxsF\nKNFX6By4gbfzz5dWovzUgoCXuf1S5T2FrCgs0jE/NbzrkZ5egNERxMUsbIuVTOIP\nuG5JxgSC00b0AksZHkCDeK6vCwKBgQDrp84xMbrJv7W6rRJh6sSS/ixytnqDOf7k\nulxxXzOI5jKwf04wL+5D9l7DM4AlX+KQLrAaHcQeEUq1V2IdxNQIcSP7JeI6bKho\nWNamyUrvkabTJaOIO13aL+3BU+Aanf0s06ryTJdy2AU5ME459Z8GDdh8FX+3CA6d\npTin+9GIdwKBgCHz/zTyHXOWWVg1qPGVV0iHLXUUnp5a4LboG/nFtSYdNHWtAoG3\n5nDp7eQsw1yW1y4uK7WJG4ihi6sU1TZgMVMnpc4AOJbHCEOo0uem10ESdYbaZVlV\nF4Jj06FpExVnwqLxqQ/J5k3Dr9tNM2YmkCIHOSHBcXUEUdbkpxQm1vhLAoGBAM6G\ntjJu/uCpXz9HRwEBm12n3JR8UEqJnVYf7bx+Ts//zxTXvVKF7y8o0EwK6pfWvNzX\nzgZVZ/dh+DONbbPhOGJdpccJoIbLi5xHn3d0mnPzFl2ecv+F5+68aoYwWAt7wtJy\nfzLy5RgFMi64oxYwqTnJEJ1OyitCqGyIzGqMS0ppAoGACT7RDC0X/QhmM/qCf0Tz\nRMu7W4uZj63NVbdqwPYMSURl/oPeON5xXSqrLmb+R+aD+GzwABTx4ty4DvpJykL1\nizpSHehswgISj/b6EwI6GmqVIvQG830xStuejCXRZ/IucPR1C13u0xt5JvoMJwJ0\nnBWy/w7F7Nydf12pLcrFoNI=\n-----END PRIVATE KEY-----\n"
          FOLDER_TMP_DEVELOPMENT: "./src/tmp"
          FOLDER_TMP_PRODUCTION: "./build/tmp"
          SENTRY_DSN: 'https://sentry.io'
          REDIS_URL: "redis://127.0.0.1:6379"
